name: deployment-workflow.yaml

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: self-hosted
    steps:
      - name : Hello, World!
        run:
          echo "Hello, World!"" >> hello.log
